export const  SET_ALERT_ACTION = 'SET_ALERT_ACTION'
export const  REMOVE_ALERT_ACTION = 'REMOVE_ALERT_ACTION'

export const  SET_ALERT = 'SET_ALERT'
export const  REMOVE_ALERT = 'REMOVE_ALERT'

//reducers for registration

export const  REGISTER_USER = 'REGISTER_USER'
export const  REGISTER_SUCCESS_ACTION = 'REGISTER_SUCCESS_ACTION'
export const  REGISTER_FAIL_ACTION = 'REGISTER_FAIL_ACTION'
export const  LOGIN_FAIL_ACTION = 'LOGIN_FAIL_ACTION'
export const  LOGIN_SUCCESS_ACTION = 'LOGIN_SUCCESS_ACTION'

export const  REGISTER_SUCCESS = 'REGISTER_SUCCESS'

export const  LOGIN_FAIL = 'LOGIN_FAIL'
export const  LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const  LOGIN_START = 'LOGIN_START'



export const  AUTH_ERROR = 'AUTH_ERROR'

//Contact reducers
export const DELETED_CONTACT_START = 'DELETED_CONTACT_START'
export const ADD_CONTACT_START = 'ADD_CONTACT_START'
export const LOAD_CONTACT_START = 'LOAD_CONTACT_START'
// contact saga
export const ADD_CONTACT = 'ADD_CONTACT'
export const LOAD_CONTACT = 'ALL_CONTACT'
export const DELETED_CONTACT = 'DELETED_CONTACT'

export const  LOGOUT = 'LOGOUT'
export const  LOGOUT_START = 'LOGOUT_START'

export const  CLEAR_CONTACT = 'CLEAR_PROFILE'

export const EMAIL_VERIFICATION_START = 'EMAIL_VERIFICATION_START'
export const EMAIL_VERIFICATION_COMPLETED = 'EMAIL_VERIFICATION_COMPLETED'
export const EMAIL_VERIFICATION_FAILED = 'EMAIL_VERIFICATION_FAILED'